Repository maeil-mail/maeil-mail-fe, pull requests merged in 2024-11, with the labels that each got.

#111 마크다운 프리뷰 table 깨짐 현상 (issue #90)
  src/app/globals.css.ts
Labels: 리팩토링

#112 QA 사항 반영 (issue #107)
  src/_components/Home/SubscribeModal/SubscribeModalContent.tsx
  src/_components/Home/SubscribeModal/VerifyEmailInput.tsx
  src/_hooks/useCategories.ts
  src/_hooks/useEmail.ts
  src/_hooks/useSubscribe.ts
Labels: 버그, 리팩토링

#103 tanstack-query 제거 (issue #89)
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/_apis/api.ts
  src/_apis/baseUrl.ts
  src/_apis/subscriptionAPI.ts
  src/_components/Home/HomeContent.tsx
  src/_components/Home/SubscribeModal/SubscribeModalContent.tsx
  src/_components/Home/SubscribeModal/subscribeModalContent.css.ts
  src/_components/Home/TrustedBySection/TrustedBySection.tsx
  src/_components/Home/TrustedBySection/trustedBySection.css.ts
  src/_components/Policy/Privacy/Privacy.tsx
  src/_components/QuestionDetail/DetailAnswer.tsx
  src/_components/QuestionDetail/DetailCategory.tsx
  src/_components/QuestionDetail/DetailTitle.tsx
  src/_components/QuestionDetail/questionDetail.css.ts
  src/_components/common/CheckboxInput/CheckboxInput.tsx
  src/_components/common/CheckboxInput/checkboxInput.css.ts
  src/_components/common/Footer/Footer.tsx
  src/_components/common/Footer/footer.css.ts
  src/_components/common/Input/Input.tsx
  src/_components/common/Input/input.css.ts
  src/_components/common/LoadingSpinner/LoadingSpinner.tsx
  src/_components/common/Modal/Modal.tsx
  src/_components/common/Modal/ModalContent/SecretModalTrigger.tsx
  src/_components/common/RadioInput/radioInput.css.ts
  src/_constants/queryClient.ts
  src/_hooks/mutations/useAddQuestion.ts
  src/_hooks/mutations/useServerActionMutation.ts
  src/_hooks/mutations/useSubscriptionMutation.ts
  src/_hooks/mutations/useVerifyMutation.ts
  src/_hooks/queries/keys/queryKeys.ts
  src/_hooks/queries/useDetailQuestion.ts
  src/_hooks/queries/useQuestion.ts
  src/_hooks/useCategories.ts
  src/_hooks/useCategory.ts
  src/_hooks/useSubscribe.ts
  src/_pages/AllQuestionPage.tsx
  src/_pages/HomePage.tsx
  src/_utils/recordGAEvent.ts
  src/_utils/shareCurrentUrl.ts
  src/app/actions.ts
  src/app/global-error.tsx
  src/app/globals.css.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/policy/page.tsx
  src/app/policy/privacy.css.ts
  src/app/question/[slug]/error.css.ts
  src/app/question/[slug]/error.tsx
  src/app/question/[slug]/page.css.ts
  src/app/question/[slug]/page.tsx
  src/app/sitemap.ts
Labels: 리팩토링

#125 구독자 수를 데이터 페이지 컴포넌트에서 받아온 데이터로 변경 (issue #123)
  src/_components/Home/ClosingCTASection/ClosingCTASection.tsx
  src/_components/Home/HomeContent.tsx
  src/_pages/HomePage.tsx
  src/app/page.tsx
Labels: 리팩토링

#127 기업 로고 레일을 고객 반응으로 대체 (issue #126)
  src/_assets/images/companyLogo/baemin.svg
  src/_assets/images/companyLogo/coupang.svg
  src/_assets/images/companyLogo/dangn.svg
  src/_assets/images/companyLogo/kakao.svg
  src/_assets/images/companyLogo/line.svg
  src/_assets/images/companyLogo/naver.svg
  src/_assets/images/companyLogo/toss.svg
  src/_assets/images/userReaction/atom.png
  src/_assets/images/userReaction/brgndy.png
  src/_assets/images/userReaction/leesang.png
  src/_assets/images/userReaction/ryan.png
  src/_components/Home/TrustedBySection/TrustedBySection.tsx
  src/_components/Home/TrustedBySection/trustedBySection.css.ts
  src/_components/Home/UserReactionSection/UserReactionItem.tsx
  src/_components/Home/UserReactionSection/UserReactionSection.tsx
  src/_components/Home/UserReactionSection/userReactionSection.css.ts
  src/_pages/HomePage.tsx
Labels: 기능

#139 센트리 config 설정 변경 (issue #138)
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: 기능, 리팩토링

#141 구독 해지 기능 구현 (issue #129)
  src/_apis/client/APIClient.ts
  src/_apis/constants/routes.ts
  src/_apis/subscription.ts
  src/_constants/externalUrl.ts
  src/_constants/pageRoutes.ts
  src/_mocks/handlers/subscription.ts
  src/app/actions.ts
  src/app/unsubscribe/completed/page.tsx
  src/app/unsubscribe/error.css.ts
  src/app/unsubscribe/error.tsx
  src/app/unsubscribe/page.tsx
  src/app/unsubscribe/unsubscribe.css.ts
Labels: 기능

#145 고객 반응 추가 (issue #144)
  src/_assets/images/userReaction/choi.png
  src/_assets/images/userReaction/ryan.png
  src/_components/Home/UserReactionSection/UserReactionSection.tsx
Labels: 기능

#146 UI 관련 유저 피드백 반영
  src/_assets/icons/close.svg
  src/_components/Home/SubscribeModal/SubscribeModal.tsx
  src/_components/Home/SubscribeModal/SubscribeModalContent.tsx
  src/_components/Home/SubscribeModal/SuccessContent.tsx
  src/_components/Home/SubscribeModal/subscribeModalContent.css.ts
  src/_components/Home/SubscribeModal/successContent.css.ts
  src/_components/common/CheckboxInput/checkboxInput.css.ts
  src/_components/common/Modal/BaseModal.tsx
  src/app/not-found.css.ts
Labels: 기능

#151 ui 피드백 반영 및 PR 템플릿 수정 (issue #149)
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  src/_assets/icons/idea.svg
  src/_assets/icons/share.svg
  src/_components/Home/SubscribeModal/SuccessContent.tsx
  src/_components/QuestionDetail/DetailAnswer.tsx
  src/_components/QuestionDetail/questionDetail.css.ts
  src/_components/common/Footer/Footer.tsx
  src/_components/common/Nav/Nav.tsx
  src/_components/common/QuestionPageNav/index.tsx
  src/_components/common/QuestionPageNav/questionPageNav.css.ts
  src/_constants/externalUrl.ts
  src/app/globals.css.ts
  src/app/question/[slug]/error.tsx
  src/app/question/[slug]/page.tsx
  src/app/question/mine/[email]/error.tsx
  src/app/unsubscribe/completed/page.tsx
  src/app/unsubscribe/error.tsx
Labels: 기능

#148 useSubscribe 리팩토링 (issue #113)
  src/_components/common/Modal/Modal.tsx
  src/_hooks/useAdminModal.ts
  src/_hooks/useAnimation.ts
  src/_hooks/useCategories.ts
  src/_hooks/useCategory.ts
  src/_hooks/useConsent.ts
  src/_hooks/useEmail.ts
  src/_hooks/useSubscribe.ts
  src/_hooks/useVerificationNumber.ts
Labels: 리팩토링

#154 Safari 크로스 브라우징 이슈, target="_blank" 보안 취약점 해결
  src/_components/common/Footer/Footer.tsx
  src/_components/common/Footer/footer.css.ts
  src/app/layout.tsx
Labels: 기능 수정

#156 에러페이지 공통화 및 인라인 스타일 분리 (issue #142)
  src/_pages/ErrorPage/errorPage.css.ts
  src/_pages/ErrorPage/index.tsx
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/question/[slug]/error.css.ts
  src/app/question/[slug]/error.tsx
  src/app/question/mine/[email]/error.tsx
  src/app/unsubscribe/error.tsx
Labels: 리팩토링
