Repository maeil-mail/maeil-mail-fe, pull requests merged in 2024-10, with the labels that each got.

#52 디테일 페이지 레이아웃 변경 (issue #48)
  maeil-mail/src/components/common/Wrapper/wrapper.css.ts
  maeil-mail/src/pages/QuestionDetailPage/page.css.ts
  maeil_mail/package-lock.json
  maeil_mail/package.json
  maeil_mail/src/_components/MDXEditor/ForwardRefEditor.tsx
  maeil_mail/src/_components/MDXEditor/InitializedMDXEditor.tsx
  maeil_mail/src/_components/QuestionDetail/DetailAnswer.tsx
  maeil_mail/src/_components/QuestionDetail/DetailCategory.tsx
  maeil_mail/src/_components/QuestionDetail/questionDetail.css.ts
  maeil_mail/src/_components/common/Button/button.css.ts
  maeil_mail/src/_components/common/Txt/Txt.tsx
  maeil_mail/src/_components/common/Txt/txt.css.ts
  maeil_mail/src/_components/common/Wrapper/wrapper.css.ts
  maeil_mail/src/_components/error/ErrorBoundary.ts
  maeil_mail/src/_components/error/ErrorBoundaryContext.ts
  maeil_mail/src/_components/error/QueryErrorBoundary.tsx
  maeil_mail/src/_components/error/types.ts
  maeil_mail/src/_utils/codemirror/formatMarkDownContent.ts
  maeil_mail/src/app/question/[slug]/error.css.ts
  maeil_mail/src/app/question/[slug]/error.tsx
  maeil_mail/src/app/question/[slug]/page.css.ts
  maeil_mail/src/app/question/[slug]/page.tsx
Labels: 리팩토링

#55 랜딩페이지 리디자인
  maeil-mail/src/components/QuestionDetail/DetailCategory.tsx
  maeil-mail/src/components/common/Modal/BaseModal.tsx
  maeil-mail/src/components/common/Modal/ModalContent/SubscribeModalContent.tsx
  maeil-mail/src/components/common/Wrapper/wrapper.css.ts
  maeil_mail/package-lock.json
  maeil_mail/package.json
  maeil_mail/src/_assets/images/mail.svg
  maeil_mail/src/_assets/images/write.svg
  maeil_mail/src/_components/Home/ClosingCTASection/ClosingCTASection.tsx
  maeil_mail/src/_components/Home/ClosingCTASection/closingCTASection.css.ts
  maeil_mail/src/_components/Home/DescriptionSection/DescriptionSection.tsx
  maeil_mail/src/_components/Home/DescriptionSection/descriptionSection.css.ts
  maeil_mail/src/_components/Home/Footer/Footer.tsx
  maeil_mail/src/_components/Home/Footer/footer.css.ts
  maeil_mail/src/_components/Home/HeroSection/HeroSection.tsx
  maeil_mail/src/_components/Home/HeroSection/heroSection.css.ts
  maeil_mail/src/_components/Home/HomeContent.tsx
  maeil_mail/src/_components/Home/Nav/Nav.tsx
  maeil_mail/src/_components/Home/Nav/nav.css.ts
  maeil_mail/src/_components/Home/SubscribeModal/SubscribeModal.tsx
  maeil_mail/src/_components/Home/SubscribeModal/SubscribeModalContent.tsx
  maeil_mail/src/_components/Home/SubscribeModal/SuccessContent.tsx
  maeil_mail/src/_components/Home/SubscribeModal/VerifyEmailInput.tsx
  maeil_mail/src/_components/Home/SubscribeModal/subscribeModalContent.css.ts
  maeil_mail/src/_components/Home/SubscribeModal/successContent.css.ts
  maeil_mail/src/_components/Home/TrustedBySection/TrustedBySection.tsx
  maeil_mail/src/_components/Home/TrustedBySection/trustedBySection.css.ts
  maeil_mail/src/_components/Home/homeContent.css.ts
  maeil_mail/src/_components/LandingContent/LandingContent.tsx
  maeil_mail/src/_components/LandingContent/landingContent.css.ts
  maeil_mail/src/_components/MetaTag/MetaTag.tsx
  maeil_mail/src/_components/common/Button/button.css.ts
  maeil_mail/src/_components/common/CheckboxInput/CheckboxInput.tsx
  maeil_mail/src/_components/common/CheckboxInput/checkboxInput.css.ts
  maeil_mail/src/_components/common/Input/Input.tsx
  maeil_mail/src/_components/common/Input/input.css.ts
  maeil_mail/src/_components/common/Modal/BaseModal.tsx
  maeil_mail/src/_components/common/Modal/ModalContent/SubscribeModalContent.tsx
  maeil_mail/src/_components/common/Modal/modal.css.ts
  maeil_mail/src/_components/common/RadioInput/RadioInput.tsx
  maeil_mail/src/_components/common/RadioInput/radioInput.css.ts
  maeil_mail/src/_components/common/Wrapper/wrapper.css.ts
  maeil_mail/src/_hooks/useSubscribe.ts
  maeil_mail/src/app/globals.css.ts
  maeil_mail/src/app/layout.tsx
  maeil_mail/src/app/page.tsx
  package-lock.json
  package.json
Labels: 기능

#57 반응형 대응 및 로고 추가
  maeil_mail/src/_assets/images/monoLogo.svg
  maeil_mail/src/_assets/images/primaryIcon.svg
  maeil_mail/src/_assets/images/primaryLogo.svg
  maeil_mail/src/_components/Home/ClosingCTASection/closingCTASection.css.ts
  maeil_mail/src/_components/Home/DescriptionSection/DescriptionSection.tsx
  maeil_mail/src/_components/Home/DescriptionSection/descriptionSection.css.ts
  maeil_mail/src/_components/Home/Footer/Footer.tsx
  maeil_mail/src/_components/Home/Footer/footer.css.ts
  maeil_mail/src/_components/Home/HeroSection/heroSection.css.ts
  maeil_mail/src/_components/Home/Nav/Nav.tsx
  maeil_mail/src/_components/Home/Nav/nav.css.ts
  maeil_mail/src/_components/Home/TrustedBySection/trustedBySection.css.ts
  maeil_mail/src/app/page.tsx
Labels: 기능

#62 빌드시 발생하는 에러 수정 (issue #61)
  maeil_mail/package-lock.json
  maeil_mail/src/_components/MetaTag/MetaTag.tsx
  maeil_mail/src/_constants/queryClient.ts
  maeil_mail/src/_pages/HomePage.tsx
  maeil_mail/src/app/page.tsx
  maeil_mail/src/app/questions/page.tsx
Labels: 버그

#63 빌드 에러 수정후 재배포
  maeil_mail/package-lock.json
  maeil_mail/src/_components/MetaTag/MetaTag.tsx
  maeil_mail/src/_constants/queryClient.ts
  maeil_mail/src/_pages/HomePage.tsx
  maeil_mail/src/app/page.tsx
  maeil_mail/src/app/questions/page.tsx
Labels: 기능

#65 BASE URL 관련 에러 수정 (issue #64)
  maeil_mail/src/_apis/baseUrl.ts
  maeil_mail/src/_components/Home/Footer/Footer.tsx
  maeil_mail/src/_components/Home/Footer/footer.css.ts
Labels: 버그, 리팩토링

#66 BASE_URL 수정 후 재배포
  maeil_mail/src/_apis/baseUrl.ts
  maeil_mail/src/_components/Home/Footer/Footer.tsx
  maeil_mail/src/_components/Home/Footer/footer.css.ts
Labels: 버그, 리팩토링

#68 마크다운 에러 수정 (issue #67)
  maeil_mail/src/_components/QuestionDetail/DetailAnswer.tsx
Labels: 버그

#69 마크다운 에러 수정 후 재배포
  maeil_mail/src/_components/QuestionDetail/DetailAnswer.tsx
Labels: 버그

#72 favicon 및 og 이미지 적용 (issue #70)
  maeil_mail/next.config.js
  maeil_mail/public/favicon.ico
  maeil_mail/src/_components/GoogleAnalytics/GoogleAnalytics.tsx
  maeil_mail/src/app/layout.tsx
Labels: 기능

#73 og 이미지, favicon 및 GA 연동 후 재배포
  maeil_mail/next.config.js
  maeil_mail/public/favicon.ico
  maeil_mail/src/_components/GoogleAnalytics/GoogleAnalytics.tsx
  maeil_mail/src/app/layout.tsx
Labels: 기능

#75 favicon 파일 수정
  maeil_mail/src/app/favicon.ico
Labels: 리팩토링

#76 favicon 파일 수정 후 재배포
  maeil_mail/src/app/favicon.ico
Labels: 리팩토링

#82 디테일 페이지 레이아웃 수정 (issue #78)
  src/_apis/baseUrl.ts
  src/_components/QuestionDetail/questionDetail.css.ts
  src/app/globals.css.ts
Labels: 리팩토링

#87 GA 및 Sentry 연동 (issue #86)
  .gitignore
  next.config.js
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/instrumentation.ts
Labels: 기능

#91 자잘한 UI 수정
  src/_apis/baseUrl.ts
  src/_assets/images/companyLogo/baemin.svg
  src/_assets/images/companyLogo/coupang.svg
  src/_assets/images/companyLogo/dangn.svg
  src/_assets/images/companyLogo/kakao.svg
  src/_assets/images/companyLogo/line.svg
  src/_assets/images/companyLogo/naver.svg
  src/_assets/images/companyLogo/toss.svg
  src/_assets/images/developerEmoji.svg
  src/_components/Home/Footer/Footer.tsx
  src/_components/Home/Footer/footer.css.ts
  src/_components/Home/HomeContent.tsx
  src/_components/Home/HomeNav/HomeNav.tsx
  src/_components/Home/HomeNav/homeNav.css.ts
  src/_components/Home/Nav/Nav.tsx
  src/_components/Home/Nav/nav.css.ts
  src/_components/Home/SubscribeModal/SubscribeModal.tsx
  src/_components/Home/SubscribeModal/SubscribeModalContent.tsx
  src/_components/Home/SubscribeModal/SuccessContent.tsx
  src/_components/Home/SubscribeModal/successContent.css.ts
  src/_components/Home/TrustedBySection/TrustedBySection.tsx
  src/_components/Policy/Privacy/Privacy.tsx
  src/_components/QuestionDetail/DetailAnswer.tsx
  src/_components/QuestionDetail/DetailCategory.tsx
  src/_components/QuestionDetail/DetailTitle.tsx
  src/_components/QuestionDetail/QuestionDetailNav.tsx
  src/_components/QuestionDetail/questionDetail.css.ts
  src/_components/common/Button/Button.tsx
  src/_components/common/Divider/Divider.tsx
  src/_components/common/Divider/divider.css.ts
  src/_components/common/Footer/Footer.tsx
  src/_components/common/Footer/footer.css.ts
  src/_components/common/Input/Input.tsx
  src/_components/common/Input/input.css.ts
  src/_components/common/Modal/Modal.tsx
  src/_components/common/Nav/Nav.tsx
  src/_components/common/Nav/nav.css.ts
  src/_constants/externalUrl.ts
  src/_pages/HomePage.tsx
  src/_styles/vars.css.ts
  src/_utils/shareCurrentUrl.ts
  src/app/globals.css.ts
  src/app/policy/page.tsx
  src/app/question/[slug]/error.css.ts
  src/app/question/[slug]/error.tsx
  src/app/question/[slug]/page.css.ts
  src/app/question/[slug]/page.tsx
Labels: 기능

#93 GA custom event 추적 로직 추가 (issue #92)
  src/_components/Home/ClosingCTASection/ClosingCTASection.tsx
  src/_components/Home/HeroSection/HeroSection.tsx
  src/_components/Home/HomeNav/HomeNav.tsx
  src/_components/QuestionDetail/QuestionDetailNav.tsx
  src/_constants/googleAnalytics.ts
  src/_utils/recordGAEvent.ts
Labels: 설정

#99 팀소개 탭 추가
  src/_components/Home/HomeNav/HomeNav.tsx
  src/_components/common/Footer/Footer.tsx
  src/_constants/externalUrl.ts
Labels: 기능

#100 404 페이지 생성 (issue #88)
  package-lock.json
  package.json
  src/app/not-found.css.ts
  src/app/not-found.tsx
Labels: 기능

#106 마크다운 list-style: none 제거 (issue #105)
  src/app/globals.css.ts
Labels: 리팩토링

#109 개인정보처리방침 스타일링 관련하여 구독자분 피드백 반영 (issue #108)
  src/app/policy/page.tsx
  src/app/policy/privacy.css.ts
Labels: 리팩토링

#110 이메일 유효성 검증 로직 추가 (issue #104)
  src/_utils/validateEmail.ts
Labels: 리팩토링
