Repository maeil-mail/maeil-mail-fe, pull requests merged in 2025-04, with the labels that each got.

#231 Fix: 띄어쓰기 수정
  README.md
  apps/maeilmail/src/common/apis/constants/http.ts
  apps/maeilmail/src/components/home/DescriptionSection/index.tsx
  apps/maeilwiki/src/components/home/WikiSubmitModal/index.tsx
  apps/maeilwiki/src/components/wikiDetail/WikiCommentInputSection.tsx
  packages/ui/src/components/Markdown/MDEditor.tsx
Labels: 기능 수정

#235 [Refactor] API response type 선언
  apps/maeilmail/src/common/types/question.ts
  apps/maeilmail/src/components/myQuestionList/QuestionItem.tsx
  apps/maeilmail/src/components/myQuestionList/QuestionList.tsx
  apps/maeilmail/src/components/myQuestionList/apis/getMyQuestions.ts
  apps/maeilmail/src/components/questionDetail/DetailCategory.tsx
  apps/maeilmail/src/components/questionDetail/apis/getQuestionDetail.ts
  apps/maeilmail/src/components/setting/apis/getMailFrequency.ts
  apps/maeilwiki/src/common/store/apis/getMemberProfile.ts
Labels: 리팩토링

#237 카테고리 타입 오류 해결
  apps/maeilmail/src/common/types/question.ts
Labels: 버그
